env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'prettier'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
settings:
  react:
    version: '18.2'
plugins:
  - 'react'
rules:
  no-unused-vars: 'warn'
  no-console: 'warn'
  react/react-in-jsx-scope: 'off'
